services:
  - type: web
    name: ai-resume-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: PORT
        value: 5004
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
